### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Arong-gong** [HSLCY/ABSA-BERT-pair#2]
生成csv数据时候，用‘\t’制表符有问题吧
![image](https://user-images.githubusercontent.com/41175098/56860788-efdd1880-69cc-11e9-8555-c64ac38c4cad.png)

**Comment by HSLCY** [comment]
你好，不是很清楚你的问题是什么。
如果问题是在excel中没有分成几列的话，那么建议直接改用notepad++等文本编辑器打开即可，效果如下图：
![image](https://user-images.githubusercontent.com/48792690/56862091-ce365e00-69d9-11e9-8819-5c2eab53ef78.png)
P.S. Excel打开较大数据文件速度很慢不推荐，而且格式经常有问题。

**Comment by Arong-gong** [comment]
对，在excel中没有分成几列的问题。感谢大佬回答
