### ISSUE TITLE
UnicodeDecodeError on loading vocab

### ISSUE THREAD

**Issue by Vl3oss** [HSLCY/ABSA-BERT-pair#3]
![image](https://user-images.githubusercontent.com/13818773/57909087-f7952c00-78ab-11e9-8313-f7a25ebd73d9.png)

I got this error after I ran **STEP 3 TRAIN** on Windows10 machine. Not sure if it Window specific or not, but I tried it on MacOS machine and this error is not occurred. 

I solved it by adding `encoding='utf8'` in line 62 of _tokenization.py_
```
def load_vocab(vocab_file):
    """Loads a vocabulary file into a dictionary."""
    vocab = collections.OrderedDict()
    index = 0
    with open(vocab_file, "r", encoding='utf8') as reader:
        while True:
            token = convert_to_unicode(reader.readline())
            if not token:
                break
            token = token.strip()
            vocab[token] = index
            index += 1
    return vocab
```

I decided to post this here in case someone ran in to this same problem.

**Comment by HSLCY** [comment]
Thanks.

**Comment by AdamVVG** [comment]
I have the same issue but it doesn't get fixed even after adding encoding='utf8'...

Any idea why?

**Comment by ChunningDu** [comment]
Thanks

**Comment by brettsherwood** [comment]
Thank you!
