### ISSUE TITLE
Max Sequence length.

### ISSUE THREAD

**Issue by abhranil08** [HSLCY/ABSA-BERT-pair#8]
What should I do, if i have longer sentences as training examples, with length>512?

**Comment by HSLCY** [comment]
Since the pre-trained model only supports `max_seq_length=512`, you must do something to keep the length<=512.
For example, you can cut off the extra tokens beyond max_seq_length. If the tail information is important, you can cut off the middle part.

**Comment by abhranil08** [comment]
But your BertConfig class in modelling.py says:
"max_position_embeddings: The maximum sequence length that this model might
                ever be used with. Typically set this to something large just in case
                (e.g., 512 or 1024 or 2048)."

**Comment by HSLCY** [comment]
I suggest that you learn more about BERT before doing experiments related to it.

**Comment by abhranil08** [comment]
what to do if I need to save checkpoints and load them again when I start training?

**Comment by HSLCY** [comment]
something like this:

load:
![image](https://user-images.githubusercontent.com/48792690/59843030-59a0ef80-938a-11e9-84fc-c09204e10477.png)
save:
![image](https://user-images.githubusercontent.com/48792690/59843054-645b8480-938a-11e9-9491-5f985b6e6441.png)
