### ISSUE TITLE
关于semeval2014 acc计算

### ISSUE THREAD

**Issue by woyijkl1** [HSLCY/ABSA-BERT-pair#9]
您好，我阅读过semeval2014的计算过程之后，有点疑惑：
 semeval2014 acc的结果 并不是Restaurants_Test_Gold.xml 中数据的acc，而是生成了辅助数据的 test_NLI_M.csv的结果（Restaurants_Test_Gold.xml中数据的条数和test_NLI_M.csv的条数是不一样的，Restaurants_Test_Gold.xml的true_label数量和test_NLI_M.csv的true_label数量不一样）

如果是按照上面计算的acc，那么这样的acc结果是否合理

**Comment by HSLCY** [comment]
你好，semeval2014的aspect category一共有五种，Test_Gold中标注了每句句子非None的aspect category的sentiment Polarity，有一个或多个。我们生成的NLI-M则是每句句子变成了五句，每句一个aspect category。semeval2014 task4的subtask4是在给定了存在的aspect category的情况下进行情感分析，所以我们在计算Acc的时候，是去掉了None的aspect category的，所以true_label数量和Test_Gold中是相同的。可以仔细阅读evaluation.py。

**Comment by woyijkl1** [comment]
ok, get it.
读代码的时候没仔细读懂semeval_Acc，现在懂了 
谢谢
